UniTec-Python/provas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('visualizar/', views.visualizar, name='visualizar'),
    path('cadastrar/', views.cadastrar, name='cadastrar')
]

UniTec-Python/provas/models.py
from django.db import models
import base64

# Create your models here.


class Sessao(models.Model):
    sessao_usuario = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date acesso')


class Aluno(models.Model):
    sessao_usuario_id = models.ForeignKey(Sessao, on_delete=models.CASCADE)
    id_aluno = models.CharField(max_length=20)
    id_curso = models.CharField(max_length=20)
    id_materia = models.CharField(max_length=20)
    id_professor = models.CharField(max_length=20)
    id_turma = models.CharField(max_length=20)


class Professor(models.Model):
    nome_professor = models.CharField(max_length=200)
    id_professor = models.CharField(max_length=20)
    id_curso = models.CharField(max_length=20)
    id_materia = models.CharField(max_length=20)
    id_turma = models.CharField(max_length=20)


class Prova(models.Model):
    id_prova = models.CharField(max_length=20)
    id_professor = models.CharField(max_length=20)
    id_turma = models.CharField(max_length=20)
    respostas = models.BinaryField



    

UniTec-Python/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <!--===================================================================================================-->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script >
      $('.js-tilt').tilt({
        scale: 1.1
      })
    </script>
</head>
<body>


<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="{% static '/images/logo-unigoias-vertical.png' %}" width="130px" height="100px">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/bemvindo/">Início</a>
                </li>
                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="/estacionamento/">Estacionamento</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/pracaalimentacao/">Praça de Alimentação</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Provas
                    </a>
                    <div class="dropdown-menu" axria-labelledby="navbarDropdown">
                                        {%if perms.chamadas.add_sessao %}
                        <a class="dropdown-item" href="/provas/cadastrar/">Adicionar</a>
                                        {% endif %}
                        <a class="dropdown-item" href="/provas/visualizar/">Visualizar</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/financeiro/">financeiro</a>
                </li>

                {%if perms.chamadas.add_sessao %}
                <li class="nav-item">
                    <a class="nav-link " href="/chamada/">Chamada</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav collapse navbar-collapse justify-content-end">
                {% endif %}
                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a href="/logout" class="btn btn-success ">Logout</a>

                </li>
                {% endif %}

                {% if user.is_authenticated %}
                {% else %}
                <li class="nav-item">
                    <a href="/login/" class="btn btn-success">Login</a>
                </li>
                {% endif %}
            </ul>


        </div>
    </nav>
</div>
{% block content %}

{% endblock %}